// {{PLUGIN_NAME}}.tsx
// Site plugin component — extends HTMLElement as a custom element.
//
// How to adapt this template:
// 1. Rename the class to match your plugin (e.g., BestSellerBadge)
// 2. Update observedAttributes with your plugin's configurable properties (kebab-case)
// 3. Update render() to build your plugin's HTML with inline styles
// 4. Use this.getAttribute('attribute-name') to read attribute values
//
// Important:
// - Do NOT call customElements.define() — Wix handles this automatically
// - Use inline styles only — CSS imports are not supported in custom elements
// - Attributes must use kebab-case (e.g., 'display-name', 'bg-color')

class MyPlugin extends HTMLElement {
  static get observedAttributes() {
    return ['display-name'];
  }

  constructor() {
    super();
  }

  connectedCallback() {
    this.render();
  }

  attributeChangedCallback() {
    this.render();
  }

  render() {
    const displayName = this.getAttribute('display-name') || "Your Plugin's Title";

    this.innerHTML = `
      <div style="font-size: 16px; padding: 16px; border: 1px solid #ccc; border-radius: 8px; margin: 16px;">
        <h2>${displayName}</h2>
        <hr />
        <p>
          This is a Site Plugin generated by Wix CLI.<br />
          Edit your element's code to change this text.
        </p>
      </div>
    `;
  }
}

export default MyPlugin;
